# =====================================================================================
# Aplication NAme 
# =======================================================================================
spring.application.name=userservice
# Name of the Application uased in logs.monitoring microservises 

# =======================================================================================
# SERVER CONFIGURATION 
# ======================================================================================= 
server.port=2026
# Defines the port number where the spring boot application will run 
# default 8080 
# Access using http://localhost:2026/

# =======================================================================================
# DATABASE CONFIGURATION (For MySql) 
# =======================================================================================
spring.datasource.url=jdbc:mysql//localhost:3306/my_user_db_spring
# JDBC URL For MySql Connection 
# Formate:jdbc:mysql://<>host/<>port/<>database_name
spring.datasource.username=root
# MySql Username 
spring.datasource.password=Sudeer@1904
# Mysql passord
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver z
# MySql JDBC driver (Required to connect java ith MySql)

# ======================================================================================
# JPA/HIBERNET CONFIGURATION 
# ======================================================================================
spring.jpa.hibernate.ddl-auto=update
# Automatically creates/update database tables based on entity clasess 
# Options:create,update,validate,none
spring.jpa.show-sql=true
# Prints sql querier in the console usefull for debugging  
spring.jpa.database-platform=org.hibernet.dilect.MySQLDialect
# Tells hidernet to use mySql specific Sql syntax